// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0jCpc78MIOoNAVpNLhYDotrsAh67jhog',
    appId: '1:894253807669:web:e695680ea3ed3e3539d97c',
    messagingSenderId: '894253807669',
    projectId: 'weforshe-project',
    authDomain: 'weforshe-project.firebaseapp.com',
    storageBucket: 'weforshe-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoT_0w0XNBxp82dB9DAr5slu5MTDPSKko',
    appId: '1:894253807669:android:a7d166bbdc9cd77639d97c',
    messagingSenderId: '894253807669',
    projectId: 'weforshe-project',
    storageBucket: 'weforshe-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXQQxEH0oB5hJNGDEtxxHE1kA9GKfTOEo',
    appId: '1:894253807669:ios:9ea2d30f20542d3e39d97c',
    messagingSenderId: '894253807669',
    projectId: 'weforshe-project',
    storageBucket: 'weforshe-project.appspot.com',
    iosBundleId: 'com.example.weforshe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXQQxEH0oB5hJNGDEtxxHE1kA9GKfTOEo',
    appId: '1:894253807669:ios:9ea2d30f20542d3e39d97c',
    messagingSenderId: '894253807669',
    projectId: 'weforshe-project',
    storageBucket: 'weforshe-project.appspot.com',
    iosBundleId: 'com.example.weforshe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0jCpc78MIOoNAVpNLhYDotrsAh67jhog',
    appId: '1:894253807669:web:abc9f050b955e51339d97c',
    messagingSenderId: '894253807669',
    projectId: 'weforshe-project',
    authDomain: 'weforshe-project.firebaseapp.com',
    storageBucket: 'weforshe-project.appspot.com',
  );
}
